version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: OrdenCJ
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: OrdenCJ
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data